name: build go

on: [push, pull_request]

jobs:
  go_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1'
      - name: run test
        run: go build -o hello hello.go